version: '3'


services:
  # Admin app
  adminapp:
    image: node-app
    command: node app1.js
    environment:
      - PORT=3000

  # Blog app
  blogapp:
    image: node-app
    command: node app2.js
    environment:
      - PORT=3001

  # Normal photo app
  photoapp1:
    image: node-app
    command: node app3.js
    environment: 
      - PORT=5000

  # Clustered photo app
  photoapp2:
    image: node-app
    command: node app4.js
    environment: 
      - PORT=5001

  # Load balanced and cached
  photoapp3:
    image: node-app
    command: node app5.js
    environment: 
      - PORT=5002

  photoapp4:
    image: node-app
    command: node app5.js
    environment: 
      - PORT=5003

  #Clustered, load balanced and cached
  photoapp5:
    image: node-app
    command: node app6.js
    environment: 
      - PORT=5004

  photoapp6:
    image: node-app
    command: node app6.js
    environment: 
      - PORT=5005
  # nginx load balancer for app 5
  lb1:
    image: nginx:latest
    restart: always # restart on reboot
    volumes:
      - './load-balance-conf/nginx1.conf:/etc/nginx/nginx.conf'
    ports:
      - '8080:80' # 8080 for outer OPS (operating system) localhost 80 for inner
    depends_on:
      - adminapp
      - blogapp
      - photoapp1
      - photoapp2
      - photoapp3
      - photoapp4
  # nginx load balancer for app 6
  lb2:
    image: nginx:latest
    restart: always # restart on reboot
    volumes:
      - './load-balance-conf/nginx2.conf:/etc/nginx/nginx.conf'
    ports:
      - '8081:80'
    depends_on:
      - adminapp
      - blogapp
      - photoapp1
      - photoapp2
      - photoapp5
      - photoapp6

  # database
#   db:
#     image: mysql:latest
#     restart: always
#     environment:
#     - MYSQL_ROOT_PASSWORD=password
#     volumes:
#       - dbvol:/var/lib/mysql

# volumes:
#   dbvol:
    